pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        google()
        mavenCentral()
        maven { url 'https://your-custom-maven-repo-url-if-any' }
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "AppSchedule"
include(":app")

