// App-level build.gradle

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'dagger.hilt.android.plugin'
//apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 35

    defaultConfig {
        namespace "com.meldcx.appschedule"
        minSdkVersion 26
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    viewBinding {
        enabled = true
    }

    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.0' // Use latest Compose compiler version
    }

    kotlinOptions {
        jvmTarget = "17"
    }
    kotlin {
        jvmToolchain(17)
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

dependencies {
    implementation libs.kotlin.stdlib
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
    implementation libs.kotlinx.coroutines.android

    implementation libs.androidx.core.ktx.v1120
    implementation libs.androidx.appcompat.v161
    implementation libs.androidx.recyclerview.v131

    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.ktx  // For Fragment viewModels() delegate

    implementation libs.androidx.material3

    implementation libs.androidx.cardview

    // Replace kapt with ksp for Room compiler
    //ksp libs.androidx.room.compiler
    implementation "androidx.room:room-runtime:2.5.2"
    implementation "androidx.room:room-ktx:2.5.2"
    ksp "androidx.room:room-compiler:2.5.2"

    implementation libs.material // or latest version
    implementation libs.hilt.android
    annotationProcessor libs.hilt.compiler
    implementation libs.lottie
    implementation libs.gson
    implementation 'com.github.Armen101:AudioRecordView:1.0.5'
    implementation "androidx.work:work-runtime-ktx:2.9.0"
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    //kapt 'com.github.bumptech.glide:compiler:4.16.0' // Only if you're using annotations (optional)
    implementation "androidx.work:work-runtime-ktx:2.9.0"

}